services:
  finlight:
    image: ghcr.io/dsaltares/finlight:main
    ports:
      - '3010:3010'
    volumes:
      - ${DATA_PATH:-finlight-data}:/data
    env_file:
      - .env
    environment:
      - DATABASE_URL=/data/db.sqlite
    restart: unless-stopped

volumes:
  finlight-data:
